image:
  file: .gitpod.Dockerfile
tasks:
  - init: npm ci
    command: npm run build && PATH=$HOME/.platformio/penv/bin:$HOME/.local/bin:$PATH && node server/app.js
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
